# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rss_postgres
    environment:
      POSTGRES_DB: rss_aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yoyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: rss_backend
    environment:
      - DATABASE_URL=postgresql://postgres:yoyo@db:5432/rss_aggregator
      - FETCH_TIME=08:00
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        python -m alembic upgrade head &&
        python seed_feeds.py &&
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: rss_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: